export {default as Happy} from './Happy'
export {default as Awestruck} from './Awestruck'
export {default as Sad} from './Sad'
export {default as Angry} from './Angry'
export {default as Indifferent} from './Indifferent'